import { UserProps } from "@/components/ChatHanger/User";

export const initialUsers: Omit<UserProps, "type">[] = [
    {
        src: "https://chirps-chat.sirv.com/termite.png",
        name: "Termite",
        status: "online",
        userType: "user",
        // hasNewMessage: true,
        messagePreview: "Hey! I just saw your latest post about the new feature. That's really cool! Can we discuss it further?",
    },
    {
        src: "https://chirps-chat.sirv.com/harambe.png",
        name: "Harambe",
        status: "online",
        userType: "room",
    },
    {
        src: "https://chirps-chat.sirv.com/frog.png",
        name: "Frog",
        status: "online",
        userType: "user",
    },
    {
        src: "https://chirps-chat.sirv.com/octopus.png",
        name: "Octopus",
        status: "online",
        userType: "user",
    },
    {
        src: "https://chirps-chat.sirv.com/parrot.png",
        name: "Parrot",
        status: "online",
        userType: "user",
    },
    {
        src: "https://chirps-chat.sirv.com/panda.png",
        name: "Panda01",
        status: "online",
        userType: "user",
    },
    {
        src: "https://chirps-chat.sirv.com/panda.png",
        name: "Panda02",
        status: "online",
        userType: "user",
    },
    {
        src: "https://chirps-chat.sirv.com/panda.png",
        name: "Panda03",
        status: "online",
        userType: "bot",
    },
    {
        src: "https://chirps-chat.sirv.com/panda.png",
        name: "Panda04",
        status: "online",
        userType: "user",
    },
    {
        src: "https://chirps-chat.sirv.com/panda.png",
        name: "Panda05",
        status: "online",
    }
];

export const rooms: Omit<UserProps, "type">[] = [
    {
        src: "https://chirps-chat.sirv.com/harambe.png",
        name: "General Chat",
        status: "online",
        userType: "room",
        messagePreview: "Welcome everyone! Feel free to chat about anything here.",
        hasNewMessage: true,
        messageCount: 47,
    },
    {
        src: "https://chirps-chat.sirv.com/termite.png",
        name: "Dev Team",
        status: "online",
        userType: "room",
        messagePreview: "Termite: The new deployment is ready for review",
        messageCount: 12,
    },
    {
        src: "https://chirps-chat.sirv.com/frog.png",
        name: "Random",
        status: "online",
        userType: "room",
        messagePreview: "Frog shared a funny meme 😂",
        messageCount: 203,
    },
    {
        src: "https://chirps-chat.sirv.com/octopus.png",
        name: "Gaming Squad",
        status: "online",
        userType: "room",
        messagePreview: "Who's up for a game tonight?",
        messageCount: 89,
    },
    {
        src: "https://chirps-chat.sirv.com/parrot.png",
        name: "Music Lovers",
        status: "online",
        userType: "room",
        messagePreview: "Parrot: Check out this new album!",
        messageCount: 156,
    },
    {
        src: "https://chirps-chat.sirv.com/panda.png",
        name: "Announcements",
        status: "online",
        userType: "room",
        messagePreview: "Important update: Server maintenance scheduled",
        messageCount: 8,
    },
    {
        src: "https://chirps-chat.sirv.com/harambe.png",
        name: "Memes & Fun",
        status: "online",
        userType: "room",
        messageCount: 534,
    },
    {
        src: "https://chirps-chat.sirv.com/termite.png",
        name: "Tech Support",
        status: "online",
        userType: "room",
        messagePreview: "How do I reset my password?",
        messageCount: 23,
    },
    {
        src: "https://chirps-chat.sirv.com/frog.png",
        name: "Design Team",
        status: "online",
        userType: "room",
        messagePreview: "New mockups are ready for feedback",
        messageCount: 67,
    },
    {
        src: "https://chirps-chat.sirv.com/octopus.png",
        name: "Movie Night",
        status: "online",
        userType: "room",
        messagePreview: "What should we watch this Friday?",
        messageCount: 41,
    },
    {
        src: "https://chirps-chat.sirv.com/parrot.png",
        name: "Book Club",
        status: "online",
        userType: "room",
        messagePreview: "Parrot: Just finished chapter 5, wow!",
        messageCount: 78,
    },
    {
        src: "https://chirps-chat.sirv.com/panda.png",
        name: "Fitness & Health",
        status: "online",
        userType: "room",
        messagePreview: "Who's joining the morning workout?",
        messageCount: 92,
    },
    {
        src: "https://chirps-chat.sirv.com/harambe.png",
        name: "Food & Recipes",
        status: "online",
        userType: "room",
        messagePreview: "Harambe shared an amazing pasta recipe",
        messageCount: 145,
    },
    {
        src: "https://chirps-chat.sirv.com/termite.png",
        name: "Pet Lovers",
        status: "online",
        userType: "room",
        messagePreview: "Check out my new puppy! 🐶",
        messageCount: 312,
    },
    {
        src: "https://chirps-chat.sirv.com/frog.png",
        name: "Travel & Adventures",
        status: "online",
        userType: "room",
        messagePreview: "Just got back from Japan, AMA!",
        messageCount: 189,
    },
    {
        src: "https://chirps-chat.sirv.com/octopus.png",
        name: "Photography",
        status: "online",
        userType: "room",
        messagePreview: "Octopus: Sunset shots from today",
        messageCount: 234,
    },
    {
        src: "https://chirps-chat.sirv.com/parrot.png",
        name: "Language Exchange",
        status: "online",
        userType: "room",
        messagePreview: "Anyone want to practice Spanish?",
        messageCount: 56,
    },
    {
        src: "https://chirps-chat.sirv.com/panda.png",
        name: "Coding Help",
        status: "online",
        userType: "room",
        messagePreview: "Stuck on this React bug, need help!",
        messageCount: 167,
    },
    {
        src: "https://chirps-chat.sirv.com/harambe.png",
        name: "Art & Creativity",
        status: "online",
        userType: "room",
        messagePreview: "Work in progress, what do you think?",
        messageCount: 98,
    },
    {
        src: "https://chirps-chat.sirv.com/termite.png",
        name: "Study Group",
        status: "online",
        userType: "room",
        messagePreview: "Termite: Finals are coming up!",
        messageCount: 43,
    },
    {
        src: "https://chirps-chat.sirv.com/frog.png",
        name: "Off-Topic",
        status: "online",
        userType: "room",
        messagePreview: "Literally anything goes here",
        messageCount: 678,
    },
    {
        src: "https://chirps-chat.sirv.com/octopus.png",
        name: "Product Feedback",
        status: "online",
        userType: "room",
        messagePreview: "Love the new dark mode feature!",
        messageCount: 34,
    },
    {
        src: "https://chirps-chat.sirv.com/parrot.png",
        name: "Events Planning",
        status: "online",
        userType: "room",
        messagePreview: "Next meetup is scheduled for Saturday",
        messageCount: 29,
    },
    {
        src: "https://chirps-chat.sirv.com/panda.png",
        name: "Job Opportunities",
        status: "online",
        userType: "room",
        messagePreview: "Senior Developer position open at TechCorp",
        messageCount: 51,
    },
    {
        src: "https://chirps-chat.sirv.com/harambe.png",
        name: "Science & Tech",
        status: "online",
        userType: "room",
        messagePreview: "Did you see the latest SpaceX launch?",
        messageCount: 127,
    },
    {
        src: "https://chirps-chat.sirv.com/termite.png",
        name: "Sports Talk",
        status: "online",
        userType: "room",
        messagePreview: "What a game last night!",
        messageCount: 198,
    },
    {
        src: "https://chirps-chat.sirv.com/frog.png",
        name: "Gardening Tips",
        status: "online",
        userType: "room",
        messagePreview: "Frog: My tomatoes are finally growing!",
        messageCount: 72,
    },
    {
        src: "https://chirps-chat.sirv.com/octopus.png",
        name: "DIY Projects",
        status: "online",
        userType: "room",
        messagePreview: "Just built a custom PC setup",
        messageCount: 115,
    },
    {
        src: "https://chirps-chat.sirv.com/parrot.png",
        name: "Mental Health",
        status: "online",
        userType: "room",
        messagePreview: "Remember to take breaks and practice self-care",
        messageCount: 64,
    },
    {
        src: "https://chirps-chat.sirv.com/panda.png",
        name: "Daily Standup",
        status: "online",
        userType: "room",
        messagePreview: "Panda01: Working on the authentication module today",
        messageCount: 18,
    },
];

export const channelMembers: Omit<UserProps, "type">[] = [
    {
        src: "https://chirps-chat.sirv.com/termite.png",
        name: "Termite",
        status: "online",
        userType: "user",
        role: "owner",
    },
    {
        src: "https://chirps-chat.sirv.com/harambe.png",
        name: "Harambe",
        status: "online",
        userType: "user",
        role: "admin",
    },
    {
        src: "https://chirps-chat.sirv.com/frog.png",
        name: "Frog",
        status: "away",
        userType: "user",
        role: "mod",
    },
    {
        src: "https://chirps-chat.sirv.com/octopus.png",
        name: "Octopus",
        status: "online",
        userType: "user",
        role: "member",
    },
    {
        src: "https://chirps-chat.sirv.com/parrot.png",
        name: "Parrot",
        status: "offline",
        userType: "user",
        role: "member",
    },
    {
        src: "https://chirps-chat.sirv.com/panda.png",
        name: "Panda01",
        status: "online",
        userType: "user",
        role: "member",
    },
    {
        src: "https://chirps-chat.sirv.com/panda.png",
        name: "Panda02",
        status: "away",
        userType: "user",
        role: "member",
    },
    {
        src: "https://chirps-chat.sirv.com/panda.png",
        name: "Panda03",
        status: "online",
        userType: "bot",
        role: "member",
    },
    {
        src: "https://chirps-chat.sirv.com/panda.png",
        name: "Panda04",
        status: "offline",
        userType: "user",
        role: "member",
    },
    {
        src: "https://chirps-chat.sirv.com/panda.png",
        name: "Panda05",
        status: "online",
        userType: "user",
        role: "member",
    },
    {
        src: "https://chirps-chat.sirv.com/termite.png",
        name: "TermiteFan",
        status: "online",
        userType: "user",
        role: "member",
    },
    {
        src: "https://chirps-chat.sirv.com/frog.png",
        name: "FroggyStyle",
        status: "away",
        userType: "user",
        role: "member",
    },
    {
        src: "https://chirps-chat.sirv.com/octopus.png",
        name: "OctoGamer",
        status: "online",
        userType: "user",
        role: "member",
    },
    {
        src: "https://chirps-chat.sirv.com/parrot.png",
        name: "ParrotHead",
        status: "offline",
        userType: "user",
        role: "member",
    },
    {
        src: "https://chirps-chat.sirv.com/harambe.png",
        name: "HarambeForever",
        status: "online",
        userType: "user",
        role: "member",
    },
];

interface Conversation {
    id: string;
    url: string;
    size: "xs" | "sm" | "md" | "lg" | "xl" | "xxl";
    name: string;
    message?: string;
    hasUnread?: boolean;
    unreadCount?: number;
    timestamp?: string;
    isYou?: boolean;
    messageStatus?: "sent" | "delivered" | "seen";
    isTyping?: boolean;
}

export const InitialConversations: Conversation[] = [
    {
        id: "1",
        url: "https://chirps-chat.sirv.com/fox.png",
        size: "lg",
        name: "Guacamolli",
        message: "Great spirits have always encounte...",
        timestamp: "2025-12-03T23:30:00",
    },
    {
        id: "2",
        url: "https://chirps-chat.sirv.com/bat.png",
        size: "lg",
        name: "Flo-Jo",
        hasUnread: true,
        unreadCount: 3,
        message: "Eighty percent of success is showin...",
        timestamp: "2025-12-03T12:00:00",
    },
    {
        id: "3",
        url: "https://chirps-chat.sirv.com/bull.png",
        size: "lg",
        name: "Mattylce",
        isYou: true,
        messageStatus: "seen",
        message: "Hey!",
        timestamp: "2024-12-03T09:00:00",
    },
    {
        id: "4",
        url: "https://chirps-chat.sirv.com/bug.png",
        size: "lg",
        name: "Passage Lovers",
        message: "Guacamolli: Great spirits have alway...",
        timestamp: "2025-12-01T18:00:00",
    },
    {
        id: "5",
        url: "https://chirps-chat.sirv.com/termite.png",
        size: "lg",
        name: "TheChief",
        message: "Anyways, that's my two cents plan f...",
        timestamp: "2025-12-04T14:00:00",
    },
    {
        id: "6",
        url: "https://chirps-chat.sirv.com/frog.png",
        size: "lg",
        name: "Butterbean",
        isTyping: true,
        timestamp: "2024-12-04T00:05:00",
    },
    {
        id: "7",
        url: "https://chirps-chat.sirv.com/guinea-pig.png",
        size: "lg",
        name: "Sarah Chen",
        isYou: true,
        messageStatus: "delivered",
        message: "Thanks for the update!",
        timestamp: "2022-09-16T10:30:00",
    },
    {
        id: "8",
        url: "https://chirps-chat.sirv.com/fly.png",
        size: "lg",
        name: "Favour Ajokubi",
        message: "Lorem ipsum, dolor sit amet consectetur adipisicing elit. Beatae, minima.",
    },
    {
        id: "9",
        url: "https://chirps-chat.sirv.com/octopus.png",
        size: "lg",
        name: "Favour Ajokubi 2",
        message: "Lorem ipsum, dolor sit amet consectetur adipisicing elit. Beatae, minima.",
    },
    {
        id: "10",
        url: "https://chirps-chat.sirv.com/fish.png",
        size: "lg",
        name: "Favour Ajokubi 3",
        message: "Lorem ipsum, dolor sit amet consectetur adipisicing elit. Beatae, minima.",
    },
    {
        id: "11",
        url: "https://chirps-chat.sirv.com/fish.png",
        size: "lg",
        name: "Favour Ajokubi 4",
        message: "Lorem ipsum, dolor sit amet consectetur adipisicing elit. Beatae, minima.",
    },
    {
        id: "12",
        url: "https://chirps-chat.sirv.com/fish.png",
        size: "lg",
        name: "Favour Ajokubi 5",
        message: "Lorem ipsum, dolor sit amet consectetur adipisicing elit. Beatae, minima.",
    },
    {
        id: "13",
        url: "https://chirps-chat.sirv.com/fish.png",
        size: "lg",
        name: "Favour Ajokubi 6",
        message: "Lorem ipsum, dolor sit amet consectetur adipisicing elit. Beatae, minima.",
    },
];


export const allResults = [
    { id: "user-1", type: "user" as const, name: "Favour Ajokubi" },
    { id: "user-2", type: "user" as const, name: "John Doe" },
    { id: "user-3", type: "user" as const, name: "Sarah Chen" },
    { id: "room-1", type: "room" as const, name: "Octagon Squad" },
    { id: "room-2", type: "room" as const, name: "Dev Team" },
    { id: "room-3", type: "room" as const, name: "Design Hub" },
    { id: "room-4", type: "room" as const, name: "Marketing" },
    { id: "channel-1", type: "channel" as const, name: "General" },
    { id: "channel-2", type: "channel" as const, name: "Random" },
    { id: "channel-3", type: "channel" as const, name: "Announcements" },
];

interface Channel {
    id: string;
    name: string;
    type: "text" | "voice";
    unread?: number;
}

export const channels: Channel[] = [
    { id: "2", name: "announcements", type: "text" },
    { id: "3", name: "random", type: "text", unread: 12 },
    { id: "4", name: "voice-chat", type: "voice" },
    { id: "5", name: "gaming", type: "voice" },
    { id: "6", name: "movies", type: "text" },
    { id: "7", name: "books", type: "text" },
    { id: "8", name: "music", type: "text" },
    { id: "9", name: "food", type: "text" },
    { id: "10", name: "travel", type: "text" },
    { id: "11", name: "sports", type: "text" },
    { id: "12", name: "coding", type: "text" },
    { id: "13", name: "bitcoin", type: "text" },
    { id: "14", name: "ethereum", type: "text" },
    { id: "15", name: "gaming-2", type: "voice" },
    { id: "16", name: "gaming-3", type: "voice" },
    { id: "17", name: "gaming-4", type: "voice" },
    { id: "18", name: "gaming-5", type: "voice" },
    { id: "19", name: "gaming-6", type: "voice" },
    { id: "20", name: "gaming-7", type: "voice" },
    { id: "21", name: "gaming-8", type: "voice" },
    { id: "22", name: "gaming-9", type: "voice" },
    { id: "23", name: "gaming-10", type: "voice" },
    { id: "24", name: "gaming-11", type: "voice" },
    { id: "25", name: "gaming-12", type: "voice" },
    { id: "26", name: "gaming-13", type: "voice" },
    { id: "27", name: "gaming-14", type: "voice" },
    { id: "28", name: "gaming-15", type: "voice" },
    { id: "29", name: "gaming-16", type: "voice" },
    { id: "30", name: "gaming-17", type: "voice" },
    { id: "31", name: "gaming-18", type: "voice" },
    { id: "32", name: "gaming-19", type: "voice" },
    { id: "33", name: "gaming-20", type: "voice" },
];