import type { Metadata } from "next";
import "./stylesheets/globals.css";
import "./stylesheets/fonts.css";

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en">
            <body
                className={`poppins antialiased`}
            >
                {children}
            </body>
        </html>
    );
}
