export enum LocalStorageKeys {
    FULLSCREEN="fullscreen",
}

export enum SearchParamKeys {
    MEMBERS_AREA="members-area",
    FULLSCREEN="fullscreen",
    ACTIVITYBAR="activitybar",
    HIDE_MENU="hide-menu",
    CHANNEL="channel",
    USER="user",
    VIEWING_PROFILE="viewing-profile",
    INVITE="invite",
    NEWPOST="newpost",
    TO="to",
    SETTINGS="settings",
    TAB="tab",
    CREATE_CHANNEL="create-channel",
    NOTIFICATIONS="notifications",
    PRIVACY="privacy",
    CHANNEL_SETTINGS="channel-settings",
    CHANNEL_NAME="channel-name",
    NEW_SUGGESTION="new-suggestion",
    SUGGESTION_ID="suggestion-id",
    SUGGESTION_TAB="suggestion-tab",
    SUGGESTION_SORT="suggestion-sort",
    SUGGESTION_FILTER="suggestion-filter",
    // Wallet modals
    WALLET_TOP_UP="wallet-top-up",
    WALLET_TRANSFER="wallet-transfer",
    WALLET_QR="wallet-qr",
    WALLET_ALL_USERS="wallet-all-users",
    WALLET_ALL_TXS="wallet-all-txs",
    WALLET_TX_DETAIL="wallet-tx-detail",
}